#baseurl = "https://lituya.netlify.com"
baseurl = "https://nordictugcharter.com"
languageCode = "en-us"
title = "Lituya: Charter Cruise Adventures in Southeast Alaska on a Nordic Tug 42"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Lituya Nordic Tug Charters"
	description = "Lituya is a Nordic Tug 42 boat available for boat and fishing charters in Southeast Alaska."

	# The path must be relative to the static folder
	favicon = "favicon.png"


	# Navigation
	[params.navigation]
		brand = "Lituya"

		[params.navigation.links]
			services  = "Onboard"
			#portfolio = "Portfolio"
			gallery = "Gallery"
			about     = "Charters"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Lituya<br>Adventures in<br>Southeast Alaska"
		subtitle   = "Explore Southeast Alaska aboard Lituya, a classic Nordic Tug 42 based in Juneau, AK. Available for bareboat and skippered charters."
		buttonText = "More Info"

	# Service section
	[params.services]
		headline = "Onboard Lituya"

        [[params.services.list]]
            icon = "fa-map-o"
            title = "Explore"
            description = "Glaciers, fjords, islands, and local cultures... explore the hidden gems all around Southeast Alaska."

        [[params.services.list]]
			icon = "vs vs-fish"
			title = "Fish"
			description = "Discover all five species of salmon, along with halibut, crab, and more..."

		[[params.services.list]]
            icon = "fa-camera"
            title = "Sightsee"
            description = "Wildlife abounds.  Humpback whales, brown and black bears, and orcas around every corner."

        [[params.services.list]]
            icon = "vs vs-sunrise"
            title = "Visit"
            description = "Visit Petersburg, Sitka, Gustavus, and others for unique views of life in Alaska."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Gallery section
	[params.gallery]
		headline    = "Gallery"
		dir = "/img/lituya_gallery"
		thumb = "-thumb"

	# About section
	[params.about]
		headline    = "Charter Info"
		description = "Launched in 2009, the Lituya is a 42′ Nordic Tug built by [Nordic Tugs](http://www.nordictugs.com/) of Burlington, Washington. The Lituya is fully equipped, seaworthy, and comfortable, and available out of Juneau, AK for both skippered or bare-boat charters in S.E. Alaska."
		#buttonText  = "Get started!"

    # Aside section
#	[params.aside]
#		headline = "Get the Creative Theme for Hugo"
#
#		[params.aside.button]
#			text = "Download now"
#			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Contact / Reservations"
		description = "Ready to plan your charter with us? Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "907-957-6509"
		email = "lituya.ak@gmail.com"

	# Google Maps section
	[params.location]
	latitude  = "58.382433"
	longitude = "-134.648417"
	maps_api_key = "AIzaSyBSzGDU9KAtNFyBJmkT9MxExZUwZX4_fQo"
